/**
 * notifyBillOnCreate — RTDB trigger: pushes LINE Flex notification when a
 * new bill appears under bills/{building}/{roomId}/{billId}.
 *
 * Role after the meter_data SoT refactor:
 *   This CF is now the SECONDARY notification path, used for the manual
 *   admin flow (admin types meter readings into "บิล & ชำระ" form and
 *   saves a bill directly to bills/ — no meter_data write).
 *
 *   The PRIMARY path is notifyTenantOnMeterUpload, which fires on
 *   meter_data Firestore writes (the dominant flow when admin uploads the
 *   monthly Excel).
 *
 * Coordination / dedup:
 *   When a bill is generated by the legacy meter chain
 *   (generateBillsOnMeterUpdate, status='auto_cf'), the corresponding
 *   meter_data doc was already notified by notifyTenantOnMeterUpload. We
 *   read meter_data.notifiedAt here and skip — preventing two LINE pushes
 *   per upload.
 *
 *   Existing billNotifiedAt guard remains for re-creation cases
 *   (delete + create rewrite of a bill).
 *
 * Why RTDB trigger (not Firestore for this CF):
 *   Bills live in RTDB. Firestore is asia-southeast3 — not all trigger
 *   regions support it. RTDB triggers are region-agnostic.
 */

const functions = require('firebase-functions/v1');
const admin = require('firebase-admin');
if (!admin.apps.length) admin.initializeApp();
const rtdb = admin.database();
const firestore = admin.firestore();

const { buildBillFlex } = require('./_billFlex');
const { lookupApprovedRoomUsers, pushAndRetry } = require('./_notifyHelper');

exports.notifyBillOnCreate = functions.region('asia-southeast1')
  .runWith({ secrets: ['LINE_CHANNEL_ACCESS_TOKEN'] })
  .database.ref('/bills/{building}/{roomId}/{billId}')
  .onCreate(async (snap, context) => {
    const bill = snap.val();
    const { building, roomId, billId } = context.params;

    if (!bill) return null;
    if (bill.status === 'paid') {
      return null;
    }
    if (bill.billNotifiedAt) {
      return null;
    }
    if (!bill.totalCharge || bill.totalCharge <= 0) {
      return null;
    }

    // Coordination with notifyTenantOnMeterUpload: if this bill came from
    // the meter_data CF chain AND that meter_data was already notified,
    // skip to prevent double-push.
    if (bill.meterDocId) {
      try {
        const meterDoc = await firestore.collection('meter_data').doc(bill.meterDocId).get();
        if (meterDoc.exists && meterDoc.data().notifiedAt) {
          await rtdb.ref(`bills/${building}/${roomId}/${billId}/billNotifiedAt`).set(new Date().toISOString());
          return null;
        }
      } catch (e) {
        console.warn(`meter_data dedup check failed for ${bill.meterDocId}:`, e.message);
        // fall through — better to potentially double-notify than to drop
      }
    }

    const token = process.env.LINE_CHANNEL_ACCESS_TOKEN;
    if (!token) {
      console.warn('⚠️ LINE_CHANNEL_ACCESS_TOKEN not set — skip notify');
      return null;
    }

    const { docs: userDocs, error: lookupErr } = await lookupApprovedRoomUsers(firestore, building, roomId);
    if (lookupErr) {
      console.error(`❌ liffUsers query failed for ${building}/${roomId}:`, lookupErr);
      return null;
    }
    if (!userDocs.length) return null;

    const tenantSnap = await firestore.collection('tenants').doc(building).collection('list').doc(String(roomId)).get();
    const tenantName = tenantSnap.exists ? (tenantSnap.data()?.name || '') : '';

    const flexMsg = buildBillFlex(bill, { tenantName });
    const { pushed, failed } = await pushAndRetry({
      docs: userDocs,
      message: flexMsg,
      token,
      source: 'notifyBillOnCreate',
      context: { building, roomId, billId },
      idempotencyKeyFn: (userId) => `bill-${building}-${roomId}-${billId}-${userId}`,
    });

    if (pushed > 0) {
      await rtdb.ref(`bills/${building}/${roomId}/${billId}/billNotifiedAt`).set(new Date().toISOString());
    }
    return { pushed, failed };
  });
