/**
 * notifyBillOnCreate — RTDB trigger: pushes LINE Flex notification when a
 * new bill appears under bills/{building}/{roomId}/{billId}.
 *
 * Role after the meter_data SoT refactor:
 *   This CF is now the SECONDARY notification path, used for the manual
 *   admin flow (admin types meter readings into "บิล & ชำระ" form and
 *   saves a bill directly to bills/ — no meter_data write).
 *
 *   The PRIMARY path is notifyTenantOnMeterUpload, which fires on
 *   meter_data Firestore writes (the dominant flow when admin uploads the
 *   monthly Excel).
 *
 * Coordination / dedup:
 *   When a bill is generated by the legacy meter chain
 *   (generateBillsOnMeterUpdate, status='auto_cf'), the corresponding
 *   meter_data doc was already notified by notifyTenantOnMeterUpload. We
 *   read meter_data.notifiedAt here and skip — preventing two LINE pushes
 *   per upload.
 *
 *   Existing billNotifiedAt guard remains for re-creation cases
 *   (delete + create rewrite of a bill).
 *
 * Why RTDB trigger (not Firestore for this CF):
 *   Bills live in RTDB. Firestore is asia-southeast3 — not all trigger
 *   regions support it. RTDB triggers are region-agnostic.
 */

const functions = require('firebase-functions');
const admin = require('firebase-admin');
if (!admin.apps.length) admin.initializeApp();
const rtdb = admin.database();
const firestore = admin.firestore();

const { buildBillFlex } = require('./_billFlex');

exports.notifyBillOnCreate = functions.region('asia-southeast1')
  .runWith({ secrets: ['LINE_CHANNEL_ACCESS_TOKEN'] })
  .database.ref('/bills/{building}/{roomId}/{billId}')
  .onCreate(async (snap, context) => {
    const bill = snap.val();
    const { building, roomId, billId } = context.params;

    if (!bill) return null;
    if (bill.status === 'paid') {
      console.log(`⏭ ${building}/${roomId}/${billId} already paid at creation — skip`);
      return null;
    }
    if (bill.billNotifiedAt) {
      console.log(`⏭ ${building}/${roomId}/${billId} already notified — skip`);
      return null;
    }
    if (!bill.totalCharge || bill.totalCharge <= 0) {
      console.log(`⏭ ${building}/${roomId}/${billId} total=0 — skip`);
      return null;
    }

    // Coordination with notifyTenantOnMeterUpload: if this bill came from
    // the meter_data CF chain AND that meter_data was already notified,
    // skip to prevent double-push.
    if (bill.meterDocId) {
      try {
        const meterDoc = await firestore.collection('meter_data').doc(bill.meterDocId).get();
        if (meterDoc.exists && meterDoc.data().notifiedAt) {
          console.log(`⏭ ${building}/${roomId}/${billId} — meter_data ${bill.meterDocId} already notified, skip`);
          await rtdb.ref(`bills/${building}/${roomId}/${billId}/billNotifiedAt`).set(new Date().toISOString());
          return null;
        }
      } catch (e) {
        console.warn(`meter_data dedup check failed for ${bill.meterDocId}:`, e.message);
        // fall through — better to potentially double-notify than to drop
      }
    }

    const token = process.env.LINE_CHANNEL_ACCESS_TOKEN;
    if (!token) {
      console.warn('⚠️ LINE_CHANNEL_ACCESS_TOKEN not set — skip notify');
      return null;
    }

    let usersSnap;
    try {
      usersSnap = await firestore.collection('liffUsers')
        .where('building', '==', building)
        .where('room', '==', String(roomId))
        .where('status', '==', 'approved')
        .get();
    } catch (e) {
      console.error(`❌ liffUsers query failed for ${building}/${roomId}:`, e.message);
      return null;
    }

    if (usersSnap.empty) {
      console.log(`ℹ️ No approved LINE-linked tenant for ${building}/${roomId} — skip`);
      return null;
    }

    const flexMsg = buildBillFlex(bill);
    const { enqueueLineRetry } = require('./_lineRetry');
    const results = await Promise.allSettled(usersSnap.docs.map(doc => {
      const lineUserId = doc.id;
      return fetch('https://api.line.me/v2/bot/message/push', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({ to: lineUserId, messages: [flexMsg] })
      }).then(r => r.ok
        ? Promise.resolve(lineUserId)
        : r.text().then(t => Promise.reject({ lineUserId, error: new Error(`LINE ${r.status}: ${t}`) }))
      );
    }));

    const pushed = results.filter(r => r.status === 'fulfilled').length;
    const failures = results.filter(r => r.status === 'rejected').map(r => r.reason);
    for (const f of failures) {
      const userId = f?.lineUserId || 'unknown';
      const errMsg = f?.error?.message || String(f);
      await enqueueLineRetry({
        lineUserId: userId,
        message: flexMsg,
        context: { source: 'notifyBillOnCreate', building, roomId, billId },
        idempotencyKey: `bill-${building}-${roomId}-${billId}-${userId}`,
        error: errMsg
      });
    }
    if (failures.length) console.warn(`⚠️ notify failures for ${building}/${roomId} (queued for retry):`, failures.length);

    if (pushed > 0) {
      await rtdb.ref(`bills/${building}/${roomId}/${billId}/billNotifiedAt`).set(new Date().toISOString());
      console.log(`📨 Bill notify sent to ${pushed} user(s) for ${building}/${roomId}/${billId}`);
    }
    return { pushed, failed: failures.length };
  });
